### ISSUE TITLE
Still getting test data error

### ISSUE THREAD

**Issue by adbeggs** [renzilin/NanoForenSTR#4]
HI

Thanks for writing this tool.

With your test command:

`python ../nanoforenstr.py LA --BAM bam_file/barcode01.test.bam --PAT pattern_file/STRtest.pat --ID test --ref ../myRef/hg19.fa --samtools samtools`

It still fails and I get:

```
## The locus D1S1656 is under inference {1/1}:   0%|                                                                                                                                                                                                    | 0/1 [00:00<?, ?it/s]/bin/sh: 1: samtools: not found
## The locus D1S1656 is under inference {1/1}:   0%|                                                                                                                                                                                                    | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "../nanoforenstr.py", line 196, in <module>
    args.func(args)
  File "../nanoforenstr.py", line 141, in LA
    seq_prefix, seq_suffix = fetch_flanking_seq(chrom, start, end, flanking_len, reference_genome, samtools)
  File "../nanoforenstr.py", line 96, in fetch_flanking_seq
    pre_flanking = faidx_output.split('\n')[1]
IndexError: list index out of range
```

**Comment by renzilin** [comment]
> HI
> 
> Thanks for writing this tool.
> 
> With your test command:
> 
> `python ../nanoforenstr.py LA --BAM bam_file/barcode01.test.bam --PAT pattern_file/STRtest.pat --ID test --ref ../myRef/hg19.fa --samtools samtools`
> 
> It still fails and I get:
> 
> ```
> ## The locus D1S1656 is under inference {1/1}:   0%|                                                                                                                                                                                                    | 0/1 [00:00<?, ?it/s]/bin/sh: 1: samtools: not found
> ## The locus D1S1656 is under inference {1/1}:   0%|                                                                                                                                                                                                    | 0/1 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "../nanoforenstr.py", line 196, in <module>
>     args.func(args)
>   File "../nanoforenstr.py", line 141, in LA
>     seq_prefix, seq_suffix = fetch_flanking_seq(chrom, start, end, flanking_len, reference_genome, samtools)
>   File "../nanoforenstr.py", line 96, in fetch_flanking_seq
>     pre_flanking = faidx_output.split('\n')[1]
> IndexError: list index out of range
> ```

I revised the installation. You can create a new env to run the code.
